# Generated by Django 6.1 on 2026-09-01 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'configuracion',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('LACTEOS', 'Lácteos'), ('CARNES', 'Carnes'), ('FRUTAS', 'Frutas'), ('VERDURAS', 'Verduras'), ('PANADERIA', 'Panadería')], max_length=50)),
                ('vida_util_dias', models.PositiveIntegerField()),
                ('proveedor', models.CharField(blank=True, default='', max_length=100)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'indexes': [models.Index(fields=['categoria'], name='idx_producto_categoria'), models.Index(fields=['activo'], name='idx_producto_activo')],
            },
        ),
        migrations.CreateModel(
            name='Merma',
            fields=[
                ('id_merma', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.FloatField()),
                ('motivo', models.CharField(choices=[('VENCIMIENTO', 'Vencimiento'), ('DANO', 'Daño'), ('ROBO', 'Robo'), ('OTRO', 'Otro')], max_length=50)),
                ('costo_perdida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='core.producto')),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
                'db_table': 'merma',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('GERENTE', 'Gerente'), ('COMPRADOR', 'Comprador')], max_length=20)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'indexes': [models.Index(fields=['correo'], name='idx_usuario_correo'), models.Index(fields=['rol'], name='idx_usuario_rol')],
            },
        ),
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id_prediccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_prediccion', models.DateField()),
                ('fecha_pronosticada', models.DateField()),
                ('valor_predicho', models.FloatField()),
                ('intervalo_inferior', models.FloatField()),
                ('intervalo_superior', models.FloatField()),
                ('precision_modelo', models.FloatField(blank=True, null=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='core.producto')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'db_table': 'prediccion',
                'indexes': [models.Index(fields=['producto', 'fecha_pronosticada'], name='idx_prediccion_prod_fecha')],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.FloatField()),
                ('lote', models.CharField(blank=True, default='', max_length=50)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='lotes_inventario', to='core.producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
                'db_table': 'inventario',
                'indexes': [models.Index(fields=['producto'], name='idx_inventario_producto'), models.Index(fields=['fecha_vencimiento'], name='idx_inventario_vencim'), models.Index(fields=['producto', 'fecha_vencimiento'], name='idx_inventario_prod_venc')],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('VENCIMIENTO', 'Vencimiento'), ('STOCK_BAJO', 'Stock bajo'), ('EXCEDENTE', 'Excedente')], max_length=20)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('accion_tomada', models.TextField(blank=True, default='')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.producto')),
                ('usuario_lector', models.ForeignKey(blank=True, db_column='id_usuario_lector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_leidas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerta',
                'indexes': [models.Index(fields=['producto'], name='idx_alerta_producto'), models.Index(fields=['leida'], name='idx_alerta_leida')],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.FloatField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promocion_aplicada', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'indexes': [models.Index(fields=['fecha'], name='idx_venta_fecha'), models.Index(fields=['producto'], name='idx_venta_producto'), models.Index(fields=['producto', 'fecha'], name='idx_venta_prod_fecha')],
            },
        ),
    ]
