# Generated by Django 6.1 on 2026-09-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AlterModelOptions(
            name='prediccion',
            options={'verbose_name': 'Predicción', 'verbose_name_plural': 'Predicciones'},
        ),
    ]
